import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { SCHEMA_SQL } from '../schemaSql.js';

function fingerprint(text) {
  return crypto.createHash('sha256').update(text, 'utf8').digest('hex').slice(0, 16);
}

function toPostgresBaselineSql(sqliteSchemaSql) {
  // Minimal compatibility transforms (keep the rest as close as possible to SQLite DDL).
  return (
    sqliteSchemaSql
      // SQLite AUTOINCREMENT -> Postgres identity
      .replace(
        /id\s+INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\s*,/gi,
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
      )
      // Make ADD COLUMN idempotent in Postgres.
      .replace(
        /\bALTER TABLE\s+([a-zA-Z0-9_]+)\s+ADD COLUMN\s+([a-zA-Z0-9_]+)/gi,
        'ALTER TABLE $1 ADD COLUMN IF NOT EXISTS $2'
      )
  );
}

function extractCreateTableBlocksFromSqliteMigrate() {
  // We use `server/migrate.js` as a source of additional CREATE TABLE blocks that are not present
  // in `server/schemaSql.js`. The JS migration file contains a lot of SQLite-only logic (PRAGMAs,
  // ALTERs, checks) but many of its CREATE TABLE statements are valid in Postgres.
  const __dirname = path.dirname(fileURLToPath(import.meta.url));
  const migratePath = path.resolve(__dirname, '..', 'migrate.js');
  const src = fs.readFileSync(migratePath, 'utf8');

  // Extract only SQL inside `db.exec(`...`)` template literals.
  // This avoids accidentally picking up JS text outside SQL blocks.
  const blocks = [];
  const execRe = /db\.exec\(\s*`([\s\S]*?)`\s*\)/g;
  let em;
  while ((em = execRe.exec(src))) {
    const sql = em[1];
    if (!sql) continue;
    // Pull CREATE TABLE blocks from this SQL chunk.
    const createRe = /CREATE TABLE IF NOT EXISTS[\s\S]*?\);\s*/gi;
    let cm;
    while ((cm = createRe.exec(sql))) blocks.push(cm[0]);
  }

  if (blocks.length === 0) return '';
  return `\n\n-- Extra tables extracted from server/migrate.js\n${blocks.join('\n')}\n`;
}

function extractAlterAddColumnStatementsFromSqliteMigrate() {
  const __dirname = path.dirname(fileURLToPath(import.meta.url));
  const migratePath = path.resolve(__dirname, '..', 'migrate.js');
  const src = fs.readFileSync(migratePath, 'utf8');

  // Extract `ALTER TABLE ... ADD COLUMN ...` statements from template strings used in `db.exec(...)`.
  const stmts = [];
  const execRe = /db\.exec\(\s*`([\s\S]*?)`\s*\)/g;
  let em;
  while ((em = execRe.exec(src))) {
    const sql = em[1];
    if (!sql) continue;
    const alterRe = /ALTER TABLE\s+[a-zA-Z0-9_]+\s+ADD COLUMN\s+[^;]+;/gi;
    let am;
    while ((am = alterRe.exec(sql))) {
      stmts.push(am[0].trim());
    }
  }

  if (stmts.length === 0) return '';
  return `\n\n-- Extra ADD COLUMN statements extracted from server/migrate.js\n${stmts.join('\n')}\n`;
}

function splitSqlStatements(sql) {
  // Split on semicolons that are not inside single/double quotes.
  const out = [];
  let buf = '';
  let inS = false;
  let inD = false;
  for (let i = 0; i < sql.length; i++) {
    const c = sql[i];
    if (c === "'" && !inD) inS = !inS;
    if (c === '"' && !inS) inD = !inD;
    if (c === ';' && !inS && !inD) {
      const s = buf.trim();
      if (s) out.push(s);
      buf = '';
      continue;
    }
    buf += c;
  }
  const tail = buf.trim();
  if (tail) out.push(tail);
  return out;
}

/**
 * Applies the baseline schema to Postgres once.
 * @param {{ query: (text: string, params?: any[]) => Promise<any> }} db
 */
export async function ensurePostgresSchema(db) {
  await db.query(`
    CREATE TABLE IF NOT EXISTS zarewa_migrations (
      id TEXT PRIMARY KEY,
      applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );
  `);

  const baseline = toPostgresBaselineSql(
    SCHEMA_SQL +
      extractCreateTableBlocksFromSqliteMigrate() +
      extractAlterAddColumnStatementsFromSqliteMigrate()
  );
  const id = `baseline_${fingerprint(baseline)}`;
  const already = await db.query(`SELECT 1 FROM zarewa_migrations WHERE id = $1`, [id]);
  if (already.rowCount > 0) return;

  const pending = splitSqlStatements(baseline);
  let lastPending = pending.length + 1;
  while (pending.length > 0) {
    if (pending.length === lastPending) {
      // No progress in the last pass: surface a helpful error.
      const sample = pending.slice(0, 3).map((s) => s.slice(0, 200));
      throw new Error(
        `[pg-migrate] stuck applying baseline schema. Remaining statements: ${pending.length}. Samples: ${JSON.stringify(sample)}`
      );
    }
    lastPending = pending.length;
    const passSize = pending.length;
    for (let i = 0; i < passSize; i++) {
      const stmt = pending.shift();
      if (!stmt) continue;
      try {
        await db.query(stmt);
      } catch (e) {
        // Common case when SQLite DDL defines a table with an FK to a table declared later.
        // Postgres needs the referenced relation to exist first.
        if (e?.code === '42P01') {
          pending.push(stmt);
          continue;
        }
        // Duplicate column (ADD COLUMN already applied) — safe to ignore.
        if (e?.code === '42701') {
          continue;
        }
        throw e;
      }
    }
  }
  await db.query(`INSERT INTO zarewa_migrations (id) VALUES ($1)`, [id]);
}

